### ISSUE TITLE
Batch image conversion

### ISSUE THREAD

**Issue by loserscat** [YukihoAA/waifu2x_snowshell#1]
Now waifu2x-converter-cpp with GUI, I'm very happy! Because I use AMD graphics card.
But now it can only handle one picture, I hope you can add batch processing later.
Although I want to help you, but I am a designer, not a programmer.
And... I have translated it into Chinese, for myself.

In the last: forget my bad English.

**Comment by YukihoAA** [comment]
Hi nice to meet you @loserscat 

Actually, Snowshell supports multiple image conversion.
simply select multiple images and drag & drop in to Snowshell!
Snowshell will convert images in serial order. (only one image at same time)

By the way, if you want to support translation of Snowshell please send language ini file to my e-mail (yukiho5048@naver.com)

Have a good day.
