### ISSUE TITLE
[Suggestion] Add support for waifu2x-ncnn-vulkan

### ISSUE THREAD

**Issue by JosephTico** [YukihoAA/waifu2x_snowshell#10]
For those of us without Intel chipsets, pretty much the only solution that doesn't take forever is https://github.com/nihui/waifu2x-ncnn-vulkan.

And I really love Snowshell GUI, so it would be awesome to have support for this

**Comment by YukihoAA** [comment]
[waifu2x-Snowshell v2.2](https://github.com/YukihoAA/waifu2x_snowshell/releases/tag/v2.2) is released. Take a look!
