### ISSUE TITLE
Rename "Use CPU" on "GPU" menu to "Disable GPU"

### ISSUE THREAD

**Issue by NintendoManiac64** [YukihoAA/waifu2x_snowshell#11]
The two options under the "GPU" menu are "Use GPU" and "Use CPU".

...but a CPU is not at all a GPU.

But both a GPU and CPU _are_ processors as that's what the 'P' means in both acronyms.

Therefore would it not be more accurate to use the label "Processor" rather than "GPU"?

This would also farther sense if/when the "[Use both GPU and CPU](https://github.com/YukihoAA/waifu2x_snowshell/issues/9)" function gets added since that could then be a third option labeled something like, well, "Use both GPU and CPU". **EDIT**: ...or I guess not since you've now stated that this is not something that Snowshell will implement, so I guess we can scratch that off the list.

**Comment by YukihoAA** [comment]
It cause menu to two line. I considered that make menu as "Processor" but It is too long to put in snowshell shell windows. I considered menu name CPU or PU rather than GPU but this program is actually for non-programmer people so thay cannot understand what PU means. and CPU is just same as GPU. So actually GPU is not correct but you can guess what it works, so If there is no short name that normal people can understand, I'll just keep it.

GPU menu means actually more like Toggle GPU support. maybe Disable GPU / Use GPU is more correct

**Comment by NintendoManiac64** [comment]
Would "GPU/CPU" work, or is that also too long?

**Comment by YukihoAA** [comment]
Same.

**Comment by NintendoManiac64** [comment]
It'd be derpy sounding, but what about "G/CPU" or "C/GPU"?

**Comment by YukihoAA** [comment]
ah. actually use CPU is now correct also, in case waifu2x-converter-cpp it always use GPU if you have GPU

**Comment by YukihoAA** [comment]
ya GPU menu is full of lie

**Comment by NintendoManiac64** [comment]
> ah. actually use CPU is not correct also, in case waifu2x-converter-cpp it always use GPU if you have GPU

But cpp is using the CPU for me though when I select "use CPU", and I have a GPU that it can use as well since cpp will accordingly use my GPU when I select "use GPU".

And I also confirmed that cpp is also _only_ using my CPU when I have "use CPU" selected and not just using both.

**Comment by YukihoAA** [comment]
in cpp
use CPU:--force-openCL
use GPU: no option

so it is different that using AVX or openCL maybe you can check it by --list-processor in waifu2x-converter-cpp

**Comment by NintendoManiac64** [comment]
I do not really know how to go about doing that.

Regardless I'm just using a Pentium G3258 (2core/2thread desktop Haswell) and its built-in integrated graphics (note that all Pentiums lack AVX support) on Windows 7 SP1.

I would imagine that any Haswell architectural CPU with integrated graphics would give identical results, especially if one additionally disabled AVX in the BIOS.

**Comment by YukihoAA** [comment]
ah OK actually Use CPU use CPU i forgot i changed it before.

so I will change "Use CPU" to "Disable GPU" and will not edit GPU menu because it actually only toggle turn on/off GPU

**Comment by NintendoManiac64** [comment]
For the actual option in the menu, it might then be best to have the following:

"Enable GPU"
"Only use CPU"

If the second option instead said 'Disable GPU" then it may not be clear that using the CPU can even be an option for the end-user.

**Comment by YukihoAA** [comment]
Actually Use GPU also could have chance to use CPU with FMA or AVX. so Enable GPU is not correct also.

I changed Use GPU to Prefer GPU which is more correct.

now User can imagine Use CPU is using CPU and Prefer GPU is try to use GPU.

this is fixed by commit "9b16ab4"
