### ISSUE TITLE
[vulkan] Noize reduce will be performed even if "None" is selected for Noize reduce.

### ISSUE THREAD

**Issue by f11894** [YukihoAA/waifu2x_snowshell#12]
Since the default value of denoise level of waifu2x-ncnn-vulkan is 0, Noize reduce will be performed unless "-n -1" is added.

**Comment by YukihoAA** [comment]
is fixed by commit b284a43

New release will come after waifu2x-converter-cpp issue#218 is fixed.

**Comment by YukihoAA** [comment]
fixed by v2.2.1 release
