### ISSUE TITLE
The interface is not displayed properly

### ISSUE THREAD

**Issue by smdx** [YukihoAA/waifu2x_snowshell#22]
Hello, the interface display is abnormal when using version 2.2.2. Win10 19042.630, resolution 4k, system zoom layout 150%.

![2020-11-23_084859](https://user-images.githubusercontent.com/9279217/99921964-c16e1d80-2d68-11eb-8d86-a90c15e8f971.jpg)

**Comment by YukihoAA** [comment]
Fixed via b366d5d
