### ISSUE TITLE
Windows Defender detection as trojan

### ISSUE THREAD

**Issue by fyr77** [YukihoAA/waifu2x_snowshell#26]
**Describe the bug**
This is probably a false positive, but the latest release (2.3) gets blocked by Windows Defender for containing a trojan. According to [Virustotal](https://www.virustotal.com/gui/file/9f84066d9608b011fb5746e95fd36b4b9fe4880140b2f5053062716b5c944067/detection) no other antivirus engines detect it as such. 

**To Reproduce**
Try to use it on Windows 10 with Windows Defender enabled.

**Expected behavior**
Regular run of the application.

**Desktop (please complete the following information):**
 - CPU: Intel Core i7 6700k
 - RAM: 16GB
 - GPU: NVIDIA GeForce GTX 1080ti
 - OS: Windows 10
 - Converter: n.A.

**Comment by YukihoAA** [comment]
I checked VirusTotal today, It shows MS Defender does not perform false-positive anymore.

Please update your defender and check again thank you.

**Comment by fyr77** [comment]
My PC is still recognizing it, but VirusTotal isn't, so I assume the update hasn't been fully rolled out yet. Thanks for the info.

**Comment by YukihoAA** [comment]
I signed waifu2x-snowshell with private certificate.

It will suppress false-positive.

If you worry about false-positive with windows defender, you can re-download execute from release page

thank you.

**Comment by sabihoshi** [comment]
This is happening again on the latest release v2.6 https://www.virustotal.com/gui/file/a6773ec8ec2d5976097136f6fdd6c8cbd45a9f4da95ea7f731a116cf4b9e3736

![image](https://user-images.githubusercontent.com/25006819/200104846-1608cf27-b565-4bc7-8453-3c42fe79b2b6.png)
