### ISSUE TITLE
Windows Defender recognizes the program as virus

### ISSUE THREAD

**Issue by zhengxinhao-comp** [YukihoAA/waifu2x_snowshell#27]
Windows Defender recognizes the main program of waifu2x - Snowshell v2.3 (waifu2x_snowshell.exe) as virus (Trojan:Win32/Glupteba!ml).

**Comment by zhengxinhao-comp** [comment]
OS: Windows 10 Home Edition, 20H2 (19042.746)

**Comment by YukihoAA** [comment]
see #26

**Comment by YukihoAA** [comment]
merged to #26.
