### ISSUE TITLE
Image progress bar not showing when converting images

### ISSUE THREAD

**Issue by SatyamSSJ10** [YukihoAA/waifu2x_snowshell#28]
**Describe the bug**
It is not showing the progress table as it should. it started happening today when I used GPU (with TTA). Now it still happens without TTA
It was utilizing a 1.8GB Vram when it first happened, later on when I tried to just denoise them it was using 200 MB Vram and this is how I found that it was doing something in background, but it wasn't consuming power at all, I mean it told it is using very low power.

**Desktop (please complete the following information):**
 - CPU: [AMD Ryzen 3500]
 - RAM: [8GB]
 - GPU: [ Vega 8]
 - OS: [ Windows 10 64]
 - Converter: [ waifu2x-converter-cpp]

[Edit: Added proof that it was working on background]

**Comment by YukihoAA** [comment]
Hi, @SatyamSSJ10

I need more detail information to reproduce problem in my system.

At first. you can enable full conversion log by using "Show Conversion Log" in "Warning" menu. It will show how waifu2x working on.

Please provide me conversion options that used today.

Example>

Noise Reduction: None
Scale: x1.6, GPU: Prefer GPU
TTA: Enabled
Output: Use output folder
Warnings: Show
Language: English
Output Format: png (you can find this in right-bottom corner)

Input File: 2048x1920 PNG file with Transparent, 13.5MB

If you provide above information, I will try to reproduce your situation and fix it.

Make sure you are using lastest version (v2.3) with lastest GPU driver.

Thank you.

**Comment by SatyamSSJ10** [comment]
The setting used when the problem started happening

Noise Reduction: Low
Scale: x1.6
GPU: Prefer GPU
TTA: Enabled
Output: Use output folder
Warnings: Show
Language: English
Output Format: Jpg

Input File: 650*925 .jpg 167Kb

My GPU Driver - 21.7.2 (Latest)

This is happening even when TTA Disabled. It is certainly consuming Vram but not doing any computation
I Deleted my version of Snowshell and then redownloaded the latest version from github. still happening. 
I think the problem might be due to the new graphic driver

**Comment by YukihoAA** [comment]
I had tried same setting that you used I cannot reproduce your situation in my system.

Please use "Show Conversion Log" on Warning Menu and Capture the First few lines to make sure waifu2x-conterter-cpp works fine.
![image](https://user-images.githubusercontent.com/20253131/131208063-fd0c43bb-662d-42ff-b3d7-a25a9cac9a23.png)

**Comment by YukihoAA** [comment]
If you don't see command line prompt with Show Conversion Log, This problem is refer to waifu2x-convter-cpp.

I'd recommend try other converter (such as ncnn-vulkan) to make your this problem happens at included converter or snowshell it self.

**Comment by SatyamSSJ10** [comment]
I did as you said but it isn't showing conversion log. even in ncnn vulkan.

**Comment by YukihoAA** [comment]
Maybe It runs properly if you delete "waifu2x-converter-cpp" folder from waifu2x-snowshell directory.

also there is new binary for ncnn-vulkan you can copy-paste in to waifu2x-ncnn-vulkan folder in waifu2x-snowshell

https://github.com/nihui/waifu2x-ncnn-vulkan/releases

**Comment by SatyamSSJ10** [comment]
nope, not working

**Comment by YukihoAA** [comment]
Ok it seems there is some problems with Windows / driver working with waifu2x-snowshell's GDI functions.

It needs more time to solve so please wait in paitionce.

Also. please provide me additional info about your Windows Version.

You can find Windows Version by

`Win+R => winver.exe`

please provide me version number of windows, such as

`Windows 10 Pro 2004`

Thank you

**Comment by SatyamSSJ10** [comment]
Windows 10 home version 2004
Build 19041.329

**Comment by SatyamSSJ10** [comment]
It is working on images smaller than 680x880px JPG files, Noise : Medium, Coverter : Vulcan, scale 2x, image size <150kb
it isn't working for images of 650x925px, like when I drag & drop nothing happens

**Comment by watertianyi** [comment]
@YukihoAA input256X256 jpg
![image](https://user-images.githubusercontent.com/29244715/226507665-5a99bbc7-5cf0-43bd-87f2-c8201731f438.png)
