### ISSUE TITLE
Ukraine version in future?

### ISSUE THREAD

**Issue by kirill0ermakov** [YukihoAA/waifu2x_snowshell#29]
Hello! Maybe you can Ukraine version in future? I want and can help from this, and thanks for your great job!

**Comment by YukihoAA** [comment]
You can contribute to provide Ukraine version translation!

I'll release new version of snowshell if you can provide Ukrain translate


translation file format is down below, you can provie me translations by pull request either email me.

https://github.com/YukihoAA/waifu2x_snowshell/tree/master/waifu2x_snowshell/Lang

yukihoaa@gmail.com

**Comment by kirill0ermakov** [comment]
Cool news! I add Ukraine translate and make pull request

**Comment by YukihoAA** [comment]
Added by PR #30
