### ISSUE TITLE
Drag'n'drop doesn't work

### ISSUE THREAD

**Issue by Morroni** [YukihoAA/waifu2x_snowshell#6]
Good evening! 

I'm sorry but the snowshell is working only when I manually open files one by one. When I just drag a folder or a couple of files, nothing happens... 

Also sometimes manual opening of a file doesn't work too (in random cases, and only restart of the app can help)... 

What can I do to fix this problem? I have some folders with a few hundred images to resize, and that's too hard to open them one by one...

Thank you!

**Comment by YukihoAA** [comment]
Did you run snowshell in administrator mode? 

I need your OS and bit (like Win 10 x64)

+ your CPU and GPU model ( NVIDIA / Radeon / INTEL / AMD )

**Comment by Morroni** [comment]
Yes, I run the app in administrator mode. If I run without it, the app doesn't even launch.
My OS is Windows 10 Pro x64

CPU: AMD Ryzen 5 1600X
GPU: EVGA (NVIDIA) GeForce GTX 1060 6 Gb

I hold cursor on objects or folder (as always in another apps), drag to window, release the button, and nothing happens, just a window of the app. That's a screenshot:
![image](https://user-images.githubusercontent.com/39649532/57941861-b49d7d80-78d8-11e9-9d42-b398595edc1d.png)

**Comment by YukihoAA** [comment]
Drag & Drop is not working on administrator mode.

If snowshell is in admin mode, explorer.exe should be admin mode too. (It is how windows shell works)

where is snowshell locates? I recommend put snowshell under d:\ or c:\ (root folder of your drive)

**Comment by Morroni** [comment]
Thank you very much!
Snowshell was successfully launched in "non-administrator" mode, so Drag&Drop is working now.
The location of the Snowshell's .exe file was in "C:\Program Files\waifu2x\"
