### ISSUE TITLE
There are always some omissions when images upscaled

### ISSUE THREAD

**Issue by human342** [YukihoAA/waifu2x_snowshell#7]
Hello, I tried to upscaled 702 images using waifu2x_snowshell but only 700 images were upscaled and 2 images were not upscaled. There is a problem that If lots of (at least 500) images are tried to be upscaled, part of images (around 0.5% of total images) are not upscaled always. 
Please fix this problem. Thank you.

**Comment by YukihoAA** [comment]
Hi, @human342

I need more information to check problems.

1. Which converter did you used? waifu2x-convertr-cpp? or waifu2x-caffe?

2. Did you convert a folder that contains 702 images in single drag-and-drop or many files/folders in multiple time?

3. Your unconverted files (2files of 702 files) are working in single file conversion?

4. Please tell me your convert setting (ex: noise: low, scale: x2.0, tta: on)

**Comment by human342** [comment]
1. waifu2x-convertr-cpp 
2.  I tried to convert a folder that contains 702 images in single drag-and-drop
3. Yes. The part of images, which are not upscaled, are upscaled successfully when I retry to upscale in single file conversion. Also the part of images, which are not upscaled, are upscaled successfully when I retry to upscale a folder that contains 'the not upscaled images' using single drag-and-drop 
4. noise : midium | scale : 2.0 | Gpu : use GPU | TTA : disabled | export : Output Folder | warning : Hide warning | Language : Korean(한국어) | Converter : waifu2x-converter-cpp

**Comment by YukihoAA** [comment]
안녕하세요 @human342 님 

제가 1003개의 파일을 알려주신 정보를 토대로 변환을 진행해보았는데요, .bat 과 같이 변환이 불가능한 파일을 제외하고는 정상적으로 변환이 되어 1002개의 결과물을 보여주는 것을 확인했습니다.

변환을 시도하신 폴더의 Full Path (예: "C:\Users\user\Downloads\프리코네\캬루짤")와 변환이 되지 않았던 파일명(예: "asdfjklewdxyzxcyiioi--0--dfuhawhz__.png")을 알려주시면 다시 한번 시도해보겠습니다. (혹시라도 변환을 시도하신 폴더 안에 있는 폴더 속의 파일에서 문제가 발생한것이라면 해당 폴더의 구조도 알려주시기 바랍니다)

문제가 발생했던 파일들을 메일로 전송해주시는 것도 도움이 됩니다.

E-mail: yukihoaa@gmail.com

**Comment by human342** [comment]
제가 처음에 말했던 702개의 이미지가 있던 폴더는 이미 삭제해서 없습니다. 그래서 다른 이미지들을 다운 받아 변환을 시도했습니다. 

변환을 시도한 폴더 위치 C:\Users\zaqxs\Downloads
변환을 시도한 파일들 위치 C:\Users\zaqxs\Downloads\Amairo Islenauts Part1
변환되지 않은 파일명 EV204BE.jpg EV213GE.jpg EV214BG.jpg
문제가 발생했던 파일들을 메일로 전송해드리고 싶지만, 변환에 쓰인 재료가 天色*アイルノーツ(하늘색 아일노츠)라는 성인게임입니다. 성인게임이어도 부담감 없이 받으실 수 있다면 메일로 전송해드리겠습니다. 또는 https://exhentai.org/g/631813/3ede04af33/ 에서 다운 받으실 수 있습니다. 총 1904개의 이미지파일들 중 이름순대로 1001개까지(파일명 EV215CD까지) 잘라내어 변환을 시도하였습니다. 그래서 변환이 시도된 파일의 개수는 1001개입니다.

**Comment by YukihoAA** [comment]
안녕하세요 @human342님

해당 파일 자체의 문제이거나 파일 경로가 너무 길어서 발생한 문제가 아닐까 생각되어 자세한 정보를 여쭈어보았는데요 해당 파일이나 변환시 옵션에 대해서는, 딱히 문제점이 보이지 않습니다. 테스트 환경에서 문제 재현이 불가능하여 자세한 원인은 파악할 수 없었으나, 아무래도 해당 부분의 경우에는 waifu2x-converter-cpp에서 간헐적으로 파일 변환이 정상적으로 처리 되지 않는 오류가 발생하는 것 같습니다. 

변환시 안정성을 높이기 위해 각 파일 변환간 간격을 살짝 늘릴 예정이고, 파일 변환이 되지 않았을 경우 log파일로 남기는 옵션을 추가할 계획입니다.

**Comment by human342** [comment]
예 알겠습니다. 한가지 더 실험을 해서 알아낸 사실이 있습니다. 같은 실험에서 같은 결과가 발생하는지 궁금하여 동일 폴더를 다시 변환 시도했는데 두 번째 실험은 다른 결과가 나왔습니다. 두번째 시도에서는 EV105AI.jpg | EV113AC.jpg | EV213GF.jpg 이미지가 변환되지 않았습니다. 프로그램 개선에 도움이 되었으면 좋겠습니다.

**Comment by YukihoAA** [comment]
@human342님 안녕하세요, waifu2x-snowshell 2.1 버전이 릴리즈 되었습니다. 해당 버전을 사용해보시고 문제가 해결되신다면 알려주시면 감사하겠습니다.

**Comment by human342** [comment]
이번에도 변환되지 않은 파일들이 있었습니다. EV116CA.jpg | EV213IE.jpg 파일이 변환되지 않았습니다. 에러로그는 확실하게 잘 작동합니다. 변환되지 않은 파일 목록이 error.log에 정확하게 적혔습니다.
