### ISSUE TITLE
Results are different compared to waifu2x.udp.jp with same image and settings?

### ISSUE THREAD

**Issue by NintendoManiac64** [YukihoAA/waifu2x_snowshell#8]
I can't help but notice that the results I'm getting from snowshell are different than the results I'm getting with waifu2x.udp.jp.

One thing in particular I've also noticed is that snowshell v1.9 and v2.1 give identical results with the same settings (that is when using GPU for both), but waifu2x.udp.jp updated their algorithm in late 2018, and update that doesn't seem to be present in snowshell.

Does this mean that snowshell uses a different implementation of the waifu2x algorithm than waifu2x.udp.jp does, or has snowshell simply not had its waifu2x algorithm updated to a more recent version?

**Comment by YukihoAA** [comment]
model file is different.

Actually snowshell is not "converter" and snowshell is only doing batch processing and no relationship with converting algorithm. so you should ask in specific converter's project site. 

https://github.com/DeadSix27/waifu2x-converter-cpp

https://github.com/lltcggie/waifu2x-caffe
